import React from 'react';
import { ArrowLeft } from 'lucide-react';

interface LegalPageProps {
  type: 'privacy' | 'terms';
  onBack: () => void;
}

const LegalPages: React.FC<LegalPageProps> = ({ type, onBack }) => {
  const isPrivacy = type === 'privacy';
  const lastUpdated = new Date().toLocaleDateString();

  return (
    <div className="w-full max-w-4xl mx-auto bg-white/90 backdrop-blur-md rounded-2xl shadow-xl overflow-hidden flex flex-col h-[80vh]">
      <div className="p-6 border-b border-gray-100 flex items-center gap-4 bg-white">
        <button 
          onClick={onBack}
          className="p-2 hover:bg-gray-100 rounded-full transition-colors text-slate-600"
        >
          <ArrowLeft size={20} />
        </button>
        <h1 className="text-2xl font-serif font-bold text-slate-900">
          {isPrivacy ? 'Privacy Policy' : 'Terms of Service'}
        </h1>
      </div>

      <div className="flex-1 overflow-y-auto p-8 text-slate-700 leading-relaxed">
        <div className="prose prose-slate max-w-none">
          <p className="text-sm text-gray-500 mb-6">Last Updated: {lastUpdated}</p>

          {isPrivacy ? (
            <>
              <h3>1. Introduction</h3>
              <p>Welcome to Ikigai Pathfinder. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you visit our website and tell you about your privacy rights.</p>

              <h3>2. Data We Collect</h3>
              <p>We may collect, use, store and transfer different kinds of personal data about you which we have grouped together follows:</p>
              <ul>
                <li><strong>Identity Data:</strong> includes first name, last name, username or similar identifier (via Google Auth).</li>
                <li><strong>Contact Data:</strong> includes email address.</li>
                <li><strong>User Input Data:</strong> includes the interests, skills, and professional goals you input into our application to generate your Ikigai analysis.</li>
                <li><strong>Transaction Data:</strong> includes details about payments to and from you and other details of products you have purchased from us. <strong>We do not store credit card details; these are handled securely by Stripe.</strong></li>
              </ul>

              <h3>3. How We Use Your Data</h3>
              <p>We will only use your personal data when the law allows us to. Most commonly, we will use your personal data in the following circumstances:</p>
              <ul>
                <li>To provide the Ikigai analysis service using Artificial Intelligence (Google Gemini API).</li>
                <li>To manage your account and subscription.</li>
                <li>To improve our website and services.</li>
              </ul>

              <h3>4. Third-Party Services</h3>
              <p>We use the following third-party services:</p>
              <ul>
                <li><strong>Google Gemini API:</strong> To generate AI responses. Your input data is sent to Google for processing.</li>
                <li><strong>Supabase:</strong> For authentication and database storage.</li>
                <li><strong>Stripe:</strong> For payment processing.</li>
              </ul>

              <h3>5. Data Security</h3>
              <p>We have put in place appropriate security measures to prevent your personal data from being accidentally lost, used or accessed in an unauthorized way, altered or disclosed.</p>

              <h3>6. Contact Us</h3>
              <p>If you have any questions about this privacy policy, please contact us at: syewhite@gmail.com</p>
            </>
          ) : (
            <>
              <h3>1. Acceptance of Terms</h3>
              <p>By accessing and using Ikigai Pathfinder, you accept and agree to be bound by the terms and provision of this agreement.</p>

              <h3>2. Description of Service</h3>
              <p>Ikigai Pathfinder provides an AI-powered analysis tool to help users discover their "Ikigai" (reason for being) based on personal inputs. The service includes both free and paid ("Founder's Club") tiers.</p>

              <h3>3. AI Disclaimer</h3>
              <p><strong>The content generated by Ikigai Pathfinder is for informational and entertainment purposes only.</strong> It is generated by Artificial Intelligence and does not constitute professional career counseling, financial advice, or psychological advice. You should verify any market data or business ideas independently before taking action.</p>

              <h3>4. Subscriptions and Payments</h3>
              <ul>
                <li><strong>Billing:</strong> Payments are processed via Stripe. By subscribing, you agree to pay the fees indicated at the time of purchase.</li>
                <li><strong>Cancellation:</strong> You may cancel your subscription at any time. Your access to paid features will continue until the end of the current billing period.</li>
                <li><strong>Refunds:</strong> Refunds are handled on a case-by-case basis. Please contact support if you believe there has been an error.</li>
              </ul>

              <h3>5. User Conduct</h3>
              <p>You agree not to use the service to generate harmful, illegal, or offensive content. We reserve the right to terminate accounts that violate this policy.</p>

              <h3>6. Limitation of Liability</h3>
              <p>In no event shall Ikigai Pathfinder, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>

              <h3>7. Changes to Terms</h3>
              <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days' notice prior to any new terms taking effect.</p>

              <h3>8. Contact Us</h3>
              <p>If you have any questions about these Terms, please contact us at: syewhite@gmail.com</p>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default LegalPages;